name = "resume"
main = "worker.js"
compatibility_date = "2026-05-11"
workers_dev = true

routes = [
  { pattern = "resume.vibhakar.dev/*", zone_name = "vibhakar.dev" },
  { pattern = "resume.vibhakar.in/*",  zone_name = "vibhakar.in"  },
]

[assets]
directory = "./public"
